### ISSUE TITLE
OpenAPI gets broken when using PROXY_BASE_PATH

### ISSUE THREAD

**Issue by pocketguy** [Unleash/unleash-proxy#125]
### Describe the bug

Hi!

When I try to use `PROXY_BASE_PATH: "base-path"` with `ENABLE_OAS: "true"` all of the requests to unleash proxy which I make using OpenAPI interface return 404. 

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /base-path/base-path/proxy</pre>
</body>
</html>
```

Seem like the reason for 404 is duplicated part `/base-path` in the url. Maybe there is some misconfiguration of OpenAPI when PROXY_BASE_PATH is used

### Steps to reproduce the bug

I used similar `docker-compose.yml`:

```yaml
version: '3.8'

services:
  unleash:
    image: unleashorg/unleash-proxy
    environment:
      ENABLE_OAS: "true"
      PROXY_BASE_PATH: "base-path"
      UNLEASH_PROXY_CLIENT_KEYS: $UNLEASH_PROXY_CLIENT_KEYS
      UNLEASH_URL: $UNLEASH_URL
      UNLEASH_INSTANCE_ID: $UNLEASH_INSTANCE_ID
      UNLEASH_APP_NAME: $UNLEASH_APP_NAME
      UNLEASH_API_TOKEN: $UNLEASH_API_TOKEN
    ports:
      - 3000:3000

```

Run it and then go to http://127.0.0.1:3000/base-path/docs/openapi/

If you try to execute any request using OpenAPI Interface, it returns 404 in response

### Subscription type

None

### Hosting type

None
