### ISSUE TITLE
Getting an empty `toggles` array

### ISSUE THREAD

**Issue by snowfrogdev** [Unleash/unleash-proxy#41]
Hi,

I've set up an Unleash instance and have confirmed that it works by using Postman. When I hit `https://unleash-dev.innago.com/api/client/features` I get a `200 OK` with the following response:

```json
{
	"version": 2,
	"features": [
		{
			"strategies": [],
			"enabled": false,
			"name": "testing-toggles",
			"description": "Temporary flag for testing using Unleash for release toggles. To be deleted once experiments are done.",
			"project": "default",
			"stale": false,
			"type": "release",
			"variants": []
		}
	],
	"query": null
}
```

I've also setup a proxy. But when I hit `https://unleash-dev-proxy.innago.com/proxy` I receive a `200 OK` with the following payload:

```json
{
	"toggles": []
}
```

In both of the above API calls I do not pass a request body and only set the `Authorization` header with the proper token.

To try and debug this, I have set the log level on the proxy to `debug` and here is what the logs show when I'm hitting it:

```bash
INFO: Get enabled feature toggles for provided context [ { remoteAddress: '::ffff:10.42.1.157', properties: {} } ]
```

And here is part of my YAML file:
```yaml
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-innago-dev-innago-dev-unleash-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: innago-dev-unleash-proxy
        client: innago
        environment: dev
        workload.user.cattle.io/workloadselector: apps.deployment-innago-dev-innago-dev-unleash-proxy
    spec:
      affinity: {}
      containers:
      - env:
        - name: UNLEASH_PROXY_SECRETS
          value: REDACTED
        - name: UNLEASH_URL
          value: https://unleash-dev.innago.com/api
        - name: UNLEASH_API_TOKEN
          value: REDACTED
        - name: LOG_LEVEL
          value: debug
        image: unleashorg/unleash-proxy
        imagePullPolicy: Always
        name: container-0
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

What could cause the proxy to return an empty `toggles` array?
